Part5
nazip/leanReact pull request #1
Opened 2018-08-17 17:40 UTC by nazip

Пробовал сделать Layout как на презентации (слайд 39) :
<Header/>
<Router>
  <Route ..../>
</Router>
<Footer/>
 В этом случаи в <Router> компоненты <Header/> и <Footer/> не завернуты, поэтому (я думаю) не получается применить  <Link> и <NavLink> из react-router. 
Пришлось все в Router завернуть (в App.js это безобразие :) )
Хотелось бы какое нибудь более 'лицеприятное' решение подсмотреть где нибудь .... есть какая нибудь ссылка (хорошие практики) ?   
Может быть и так нормально конечно, но что то я сомневаюсь.
Хочется внести ястность в этом вопросе

2018-08-18 11:35 UTC, index01d requested changes

2018-08-18 11:35 UTC, index01d commented on src/ProductCard.js
> +        <Link to={`/product/${id}`}>
должен использоваться path-helper

2018-08-18 11:35 UTC, index01d commented on src/Header.js
> +                <NavLink href='/products'>Продукты</NavLink>
должны использоваться pathHelpers

2018-08-18 19:46 UTC, nazip commented
Хотел прояснить для себя как 'грамотно' работать с layout приложения:
Layout у меня состоит из 3 частей : header, body и footer.
1. пробовал использовать вложенные роуты и понял что это не работает. Может в 4 роутах это  не работает или я что то не так делааю ?    
const a = () => <div>aaa</div>
const b = () => <div>bbb</div>

export default () => (
  <Router  history={history}>
    <Route component={a}>
      <Switch>
        <Route path='/' component={b}/>
      </Switch>
    </Route>
  </Router>
);
Получаю вот такой варнинг: Warning: You should not use <Route component> and <Route children> in the same route; <Route children> will be ignored 
Даже если я ошибаюсь (склонен думать что так оно и есть :) )все равно этот способ для layout не очень подходит. Если компонент 'a' в примере это header , а  'b'  это body то не знаю как сделать footer. Другими словами нужет еще один render который всегда рендерится последним. 
2. пробовал сделать так :
<Layout>
   {children}
</Layout>

где в качестве children подавал все роуты оформленные в виде компонента.
Здесь поджидала другая засада: В Layout я описал header и footer там конечно же Link и NavLink от роутера не работают так как они оказались не обернуты роутом :))))
В итоге пришлось обернуть роутом весь layout .  Хотелось сделать как то так чтобы отделить роуты от layout или это нормально как у меня сейчас ?

2018-08-18 19:51 UTC, nazip commented
`Хотел прояснить для себя как 'грамотно' работать с layout приложения:
Layout у меня состоит из 3 частей : header, body и footer.
1. пробовал использовать вложенные роуты и понял что это не работает. Может в 4 роутах это  не работает или я что то не так делааю ?    
"const a = () => <div>aaa</div>
const b = () => <div>bbb</div>

export default () => (
  <Router  history={history}>
    <Route component={a}>
      <Switch>
        <Route path='/' component={b}/>
      </Switch>
    </Route>
  </Router>
);"

Получаю вот такой варнинг: Warning: You should not use <Route component> and <Route children> in the same route; <Route children> will be ignored 
Даже если я ошибаюсь (склонен думать что так оно и есть :) )все равно этот способ для layout не очень подходит. Если компонент 'a' в примере это header , а  'b'  это body то не знаю как сделать footer. Другими словами нужет еще один render который всегда рендерится последним. 
2. пробовал сделать так :
<Layout>
   {children}
</Layout>

где в качестве children подавал все роуты оформленные в виде компонента.
Здесь поджидала другая засада: В Layout я описал header и footer там конечно же Link и NavLink от роутера не работают так как они оказались не обернуты роутом :))))
В итоге пришлось обернуть роутом весь layout .  Хотелось сделать как то так чтобы отделить роуты от layout или это нормально как у меня сейчас ?  

`

2018-08-18 19:57 UTC, nazip commented
Хотел прояснить для себя как 'грамотно' работать с layout приложения:
Layout у меня состоит из 3 частей : header, body и footer.
1. пробовал использовать вложенные роуты и понял что это не работает. Может в 4 роутах это  не работает или я что то не так делааю ?    
"const a = () => <div>aaa</div>
const b = () => <div>bbb</div>

export default () => (
  <Router  history={history}>
    <Route component={a}>
      <Switch>
        <Route path='/' component={b}/>
      </Switch>
    </Route>
  </Router>
);"

Получаю вот такой варнинг: Warning: You should not use <Route component> and <Route children> in the same route; <Route children> will be ignored 
Даже если я ошибаюсь (склонен думать что так оно и есть :) )все равно этот способ для layout не очень подходит. Если компонент 'a' в примере это header , а  'b'  это body то не знаю как сделать footer. Другими словами нужет еще один render который всегда рендерится последним. 
2. пробовал сделать так :
<Layout>
   {children}
</Layout>

где в качестве children подавал все роуты оформленные в виде компонента.
Здесь поджидала другая засада: В Layout я описал header и footer там конечно же Link и NavLink от роутера не работают так как они оказались не обернуты роутом :))))
В итоге пришлось обернуть роутом весь layout .  Хотелось сделать как то так чтобы отделить роуты от layout или это нормально как у меня сейчас ?

2018-08-18 19:59 UTC, nazip commented
__

2018-08-18 20:17 UTC, nazip commented
Хотел прояснить для себя как 'грамотно' работать с layout приложения:
Layout у меня состоит из 3 частей : header, body и footer.
1. пробовал использовать вложенные роуты и понял что это не работает. Может в 4 роутах это  не работает или я что то не так делааю ?    
Ссылка на код (почему то код не виден здесь поэтому ссылку пришлось сделать):  https://github.com/nazip/leanReact/blob/part5/src/AppTest.js
Получаю вот такой варнинг: Warning: You should not use Route component and Route children in the same route; Route children will be ignored 

Даже если я ошибаюсь (склонен думать что так оно и есть :) )все равно этот способ для layout не очень подходит. Если компонент 'a' в примере это header , а  'b'  это body то не знаю как сделать footer. Другими словами нужет еще один render который всегда рендерится последним. 
2. пробовал layout сделать в виде компонента где в качестве children подавал все роуты оформленные в виде компонента.
Здесь поджидала другая засада: В Layout я описал header и footer там конечно же Link и NavLink от роутера не работают так как они оказались не обернуты роутом :))))
В итоге пришлось обернуть роутом весь layout .  Хотелось сделать как то так чтобы отделить роуты от layout или не стоит заморачиваться и  это и так нормально ?

2018-08-19 12:38 UTC, index01d commented
Вариант (1) не пройдет в 4 роутере, это верно
Вариант (2) вполне работоспособен, если соорудить нечто вроде
```
<Router>
  <MainLayout>
    <Switch> ... </Switch>
  </MainLayout>
</Router>
```
в этом случае проблем с Link не возникнет. Если layout отличается для разных роутов, то можно либо написать абстракцию для роутов (модифицировать RoutesWithSubroutes и подмешивать layout из свойства роута в функции render), либо создавать отдельные компоненты страниц и зашивать их в layout там.

2018-08-19 12:38 UTC, index01d commented
если будут еще вопросы на тему, то можно продолжить на форуме или в slack

2018-08-19 16:18 UTC, merged