Part6
nazip/leanReact pull request #2
Opened 2018-08-23 11:18 UTC by nazip

2018-08-23 12:13 UTC, nazip commented
API находится по адресу http://178.205.168.26:4321 
исходник API https://github.com/nazip/web1 (сделано по принципу 'лишь бы работало'  :))  )

2018-08-26 07:33 UTC, index01d commented
> Не могу понять почему с плоскими роутами не получается 404 страница (вместо этой страницы рендерится корневой роут path='/') Подскажи пожалуйста где косячу

в модуле App.js ты импортируешь роут about, который не экспортируешь из routes/index.js
Надо переделать этот модуль, экспортировать из routes/index.js сразу готовый список. Тогда подобных ошибок можно будет избежать.

> При попытке обратиться к api с несуществующим id продукта где лучше решать проблему

Бэкенд должен возвращать корректный код (404) или флаг в ответе JSON (лучше и то, и то, но в реальной практике бывает всякое); Фронтенд должен корректно обрабатывать ответ бэкенда, а также ситуации, связанные с недоступностью бэкенда.

2018-08-26 07:41 UTC, index01d requested changes
Давай побьем на директории проект:
components/views(или pages) со списком компонентов каждой страницы
внутри организуем компоненты страницы ~~ так:
CatalogPage/index.js // контейнерный компонент
CatalogPage/Catalog.js // презентационный компонент
components/shared/ с реиспользуемыми компонентами, например
components/shared/Layout/index.js - Layout

2018-08-26 07:41 UTC, index01d commented on src/App.js
>  const routes = [root, product, products, about, notFound];
нужно сформировать список в модуле routes/index

2018-08-26 07:41 UTC, index01d commented on src/ProductCard.js
> +    componentDidMount() {
презентационный компонент не должен содержать контейнерной логики, можно выделить отдельный контейнерный компонент

2018-08-26 07:41 UTC, index01d commented on src/ProductCardExt.js
> +    componentDidMount() {
презентационный компонент не должен содержать контейнерной логики

2018-08-26 07:41 UTC, index01d commented on src/routes/RoutesWithSubRoutes.js
> +        // path={route.path}
есть правило хорошего тона: никогда не оставлять закомментированный код в репозитории

2018-08-26 07:41 UTC, index01d commented on src/Catalog.js
> +            return (
стоит выделить компонент каталога

2018-08-26 07:41 UTC, index01d commented on src/Catalog.js
> +            return (
от контейнерного компонента

2018-08-26 18:25 UTC, nazip commented
Я в компонентах пути прописываю относительные если компонент лежит в том же каталоге и абсолютные если нет.  Это ОК ? или какого то другого принципа надо придерживаться ?

2018-08-27 07:17 UTC, index01d commented
> вроде логично , как думаешь ?

дело предпочтений. Лично я не выделяю каталог, пока не настало его время :)

> Я в компонентах пути прописываю относительные если компонент лежит в том же каталоге и абсолютные если нет. Это ОК ? или какого то другого принципа надо придерживаться ?

вполне ОК

2018-08-27 07:20 UTC, index01d approved these changes

2018-08-27 07:20 UTC, index01d commented on src/components/views/Basket/index.js
> +import Portal from '/src/components/views/Portal';
похоже, что Portal не должен быть во view. больше тянет на разделяемый компонент, который должен быть в shared

2018-08-27 07:20 UTC, index01d commented on src/components/views/Catalog/Product.js
> +import AddToBasket from '/src/components/views/AddToBasket';
кнопка добавления в корзину является частью карточки, поэтому вероятно должна быть в ее директории

2018-08-27 16:42 UTC, merged