Part8
nazip/leanReact pull request #4
Opened 2018-09-10 19:30 UTC by nazip

В акшенах мидлвары localstorage  есть функции (т. е. акшет не просто обьект). Может стоило логику перенести в мидлвару и тем самым сделать акшены просто обьектами ?  (но тогда теряется универсальность мидлвары) 
Надеюсь получить 'разгромный ответ' по проекту (урок по сути последний )  )  ... может научусь чему нибудь ))

2018-09-12 09:56 UTC, index01d requested changes
1) Следует устранить все случаи зависимостей actionCreator'ов, reducer'ов и презентационных компонентов от модуля store 
2) Следует устранить побочные эффекты из actionCreator'ов
3) Все изменения состояния допустимы только в коде reducer'ов
4) для middleware localStorage не требуются вспомогательные типы действий (REQUEST, SUCCESS, FAILURE), потому что сохранение и извлечение происходят синхронно
5) Не следует включать в состояние презентационных компонентов поля, которые можно определить на основе свойств и осуществлять бесполезное копирование значений

2018-09-12 09:56 UTC, index01d commented on index.html
> +        <script src="public/assets/bundle.bundle.js"></script>
название получилось избыточное

2018-09-12 09:56 UTC, index01d commented on src/redux/actions/basket.js
> +    let items = store.getState().basket.items.map((el) => {
побочный эффект, которого здесь быть не должно

2018-09-12 09:56 UTC, index01d commented on src/redux/actions/basket.js
> +            types.ADD_TO_BASKET_REQUEST,
сохранение и извлечение из localStorage происходит синхронно, эти описания действий тут попросту не нужны

2018-09-12 09:56 UTC, index01d commented on src/redux/actions/basket.js
> +    let items = store.getState().basket.items.map((el) => {
изменение состояния недопустимо в actionCreator'e. Менять состояние можно только в reducer'e и в редких случаях в middleware (это не тот редкий случай)

2018-09-12 09:56 UTC, index01d commented on src/redux/forms/OrderForm.js
> +        {store.getState().order.status == 'failure'
нельзя обращаться к store в презентационном компоненте напрямую. Готовы данные должны приходить из контейнерного компонента

2018-09-12 09:56 UTC, index01d commented on src/redux/forms/OrderForm.js
> +import store from '../store';
всякий раз, когда хочешь импортировать модуль store где-то, кроме инициализатора - это знак того, что ты нарушаешь правила игры :)

2018-09-12 09:56 UTC, index01d commented on src/redux/reducers/basket.js
> +        case type.DELETE_FROM_BASKET_SUCCESS:
reducer это не просто бесполезная функция для присваивания :) Все операции над состоянием нужно производить здесь

2018-09-12 09:56 UTC, index01d commented on src/components/views/Basket/index.js
>      constructor(props) {
из презентационного компонента корзины следует устранить собственное состояние items: [], данные должны приходить из redux-Контейнера

2018-09-12 09:56 UTC, index01d commented on src/components/views/Basket/index.js
>          this.itemsQuantity = this.itemsQuantity.bind(this);
контейнерный метод должен определяться в redux-контейнере

2018-09-12 09:56 UTC, index01d commented on src/components/views/Basket/index.js
>          this.setState({items: this.props.items});
ненужная операция

2018-09-12 09:56 UTC, index01d commented on src/components/views/Catalog/index.js
>          (this.props.items != this.state.items) &&
не нужно копировать свойства в состояние, это противоречит определению правил для включения полей в состояние компонента. Нужно использовать значения из свойств напрямую

2018-09-12 09:56 UTC, index01d commented on src/components/views/Catalog/index.js
>          } else {
выше нужно использовать значения из свойств

2018-09-12 10:26 UTC, nazip commented
"для middleware localStorage не требуются вспомогательные типы действий (REQUEST, SUCCESS, FAILURE), потому что сохранение и извлечение происходят синхронно"
Я переделаю но есть вопрос: Я понял что нужно тройка (REQUEST, SUCCESS, FAILURE) нужна при асинхронных действиях. А если из синхроного действия сделать асинхронное (т. е. promise ) тогда все ОК ?  Конечно это имеет смысл только при длительных операциях, например когда в localStorage записывают много инфы.

2018-09-14 17:09 UTC, nazip commented
Все 5 'заповедей' старался соблюсти )) .... жду оставшиеся 5 :))

2018-09-16 07:52 UTC, index01d approved these changes

2018-09-16 07:52 UTC, index01d commented on src/components/shared/Layout/Header.js
> +import {catalog, about, root, order} from '~/src/helpers/routes';
без приставки path можно словить пересечение по именам в будущем

2018-09-16 07:52 UTC, index01d commented on src/components/shared/ProductsTable.js
> +        {console.log('items=', items)}
?

2018-09-16 07:52 UTC, index01d commented on src/components/views/Basket/index.js
>      itemsQuantity() {
этот метод тоже должен быть в контейнере

2018-09-16 07:52 UTC, index01d commented on src/components/views/Basket/index.js
>      itemsQuantity() {
а точнее даже результат его вычисления должен приходить свойством

2018-09-16 17:10 UTC, merged